#
# Apple
# 



# ====================分割线====================



hostname = gspe1-ssl.ls.apple.com,dispatcher.is.autonavi.com, configuration.ls.apple.com,gspe35-ssl.ls.apple.com, uts-api.itunes.apple.com,umc-tempo-api.apple.com,play-cdn.itunes.apple.com,play-edge-cdn.itunes.apple.com,   buy.itunes.apple.com,



# ====================分割线====================



# iPhone iRingo https://github.com/NSRingo 一键BOXJS http://boxjs.com/#/sub/add/https://github.com/NSRingo/BoxJs/raw/main/iRingo.BoxJs.json

# 📍 Country Code
^https?:\/\/gspe1-ssl\.ls\.apple\.com\/pep\/gcc url script-response-body https://github.com/NSRingo/LocationService/releases/download/v1.0.1/request.bundle.js
# 📍 Dispatcher
^https?:\/\/dispatcher\.is\.autonavi\.com\/dispatcher url script-request-body https://github.com/NSRingo/LocationService/releases/download/v1.0.1/request.bundle.js
^https?:\/\/dispatcher\.is\.autonavi\.com\/dispatcher url script-response-body https://github.com/NSRingo/LocationService/releases/download/v1.0.1/response.bundle.js


# 🗺️ Network Defaults
^https?:\/\/configuration\.ls\.apple\.com\/config\/defaults url script-request-header https://github.com/NSRingo/GeoServices/releases/download/v4.6.1/request.bundle.js
^https?:\/\/configuration\.ls\.apple\.com\/config\/defaults url script-response-body https://github.com/NSRingo/GeoServices/releases/download/v4.6.1/response.bundle.js
# 🗺️ Announcements
^https?:\/\/gspe35-ssl\.ls\.apple\.(com|cn)\/config\/announcements url script-request-header https://github.com/NSRingo/GeoServices/releases/download/v4.6.1/request.bundle.js
^https?:\/\/gspe35-ssl\.ls\.apple\.(com|cn)\/config\/announcements url script-response-body https://github.com/NSRingo/GeoServices/releases/download/v4.6.1/response.bundle.js
# 🗺️ Resource Manifest
^https?:\/\/gspe35-ssl\.ls\.apple\.(com|cn)\/geo_manifest\/dynamic\/config url script-request-header https://github.com/NSRingo/GeoServices/releases/download/v4.6.1/request.bundle.js
^https?:\/\/gspe35-ssl\.ls\.apple\.(com|cn)\/geo_manifest\/dynamic\/config url script-response-body https://github.com/NSRingo/GeoServices/releases/download/v4.6.1/response.bundle.js


# 📺 TV UTS
^https?:\/\/uts-api\.itunes\.apple\.com\/uts\/(v1|v2|v3)\/ url script-request-body https://github.com/NSRingo/TV/releases/download/v3.4.4/request.bundle.js
^https?:\/\/uts-api\.itunes\.apple\.com\/uts\/(v1|v2|v3)\/ url script-response-body https://github.com/NSRingo/TV/releases/download/v3.4.4/response.bundle.js
# 📺 TV UMC
^https?:\/\/umc-tempo-api\.apple\.com\/(v1|v2|v3)\/ url script-request-body https://github.com/NSRingo/TV/releases/download/v3.4.4/request.bundle.js



# ====================分割线====================



# 熊掌记 @Guding88 https://github.com/Guding88/Script/blob/main/xiongzhangji.js
^https?:\/\/buy\.itunes\.apple\.com\/verifyReceipt$ url script-response-body https://raw.githubusercontent.com/Guding88/Script/main/xiongzhangji.js


